version: '3.8'

services:
  infra:
    image: golang
    ports:
      - "9101:9100"
    volumes:
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
        read_only: true
      - ./:/app
    working_dir: /app/
    command: "go run ./cmd/main.go"
    networks:
      - infra

networks:
  infra:
    external: true
