version: '3.8'

services:
  infra:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9101:9100"
    volumes:
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
        read_only: true
      - ./:/app
    working_dir: /app/
    command: "go run ./cmd/main.go"
    environment:
      SERVICE_NAVIGATOR_APP_NAME: Infra
      SERVICE_NAVIGATOR_NETWORK_NAME: infra
      USER: "${USER}"
    networks:
      - infra

networks:
  infra:
    external: true
