version: '3.8'

services:
  infra:
    build:
      context: .
      dockerfile: Dockerfile_local
    ports:
      - "9101:8080"
    volumes:
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
        read_only: true
      - ./:/app
    working_dir: /app/
    command: "go run ./cmd/main.go"
    environment:
      USER: "${USER}"
    networks:
      - infra

  whoami:
    image: mirror.gcr.io/jwilder/whoami
    ports:
      - "8999:8000"
    networks:
      - infra

networks:
  infra:
    external: true
